[main]
gid = 1
nid = 10
max_jobs = 100
message_id_file = "./.mid"
history_file = "./.history"
roles = []

[controllers]
    [controllers.main]
    url = "http://localhost:8966"
        [controllers.main.security]
        # UNCOMMENT THE FOLLOWING LINES TO USE SSL
        #client_certificate = "/path/to/client-test.crt"
        #client_certificate_key = "/path/to/client-test.key"

        # defines an extra CA to trust (used in case of server self-signed certs)
        # should be empty string otherwise.

        #certificate_authority = "/path/to/server.crt"

[channel]
cmds = [] # empty for long polling from all defined controllers, or specif controllers keys

[extensions]
    [extensions.sync]
    #syncthing extension
    binary = "python2.7"
    cwd = "./extensions/sync"
    script = "{name}.py"
        [extensions.sync.env]
        PYTHONPATH = "../:/opt/jumpscale7/lib"
        JUMPSCRIPTS_HOME = "/opt/jumpscale7/apps/agent2/jumpscripts/"
        SYNCTHING_URL = "http://localhost:28384"

    [extensions.jumpscript]
    binary = "python2.7"
    cwd = "./extensions/jumpscript"
    script = "wrapper.py"
    args = ["{domain}", "{name}"]
        [extensions.jumpscript.env]
        SOCKET = "/tmp/jumpscript.sock"
        PYTHONPATH = "../"

    [extensions.__jumpscript_daemon]
    binary = "python2.7"
    cwd = "./extensions/jumpscript"
    script = "executor.py"
        [extensions.__jumpscript_daemon.env]
        SOCKET = "/tmp/jumpscript.sock"
        PYTHONPATH = "../:/opt/jumpscale7/lib"
        JUMPSCRIPTS_HOME = "/opt/jumpscale7/apps/agent2/jumpscripts/"

    [extensions.legacy]
    binary = "python2.7"
    cwd = "./extensions/legacy"
    script = "wrapper.py"
        [extensions.legacy.env]
        PYTHONPATH = "../" # for utils
        SOCKET = "/tmp/legacy.sock"

    #Internal command for legacy. Will be called
    #by the agent startup.
    [extensions.__legacy_daemon]
    binary = "python2.7"
    cwd = "./extensions/legacy"
    script = "executor.py"
        [extensions.__legacy_daemon.env]
        SOCKET = "/tmp/legacy.sock"
        PYTHONPATH = "../:/opt/jumpscale7/lib"
        JUMPSCRIPTS_HOME = "/opt/jumpscale7/apps/agent2/legacy/"

[logging]
    [logging.db]
    type = "DB"
    log_dir = "./logs"
    levels = [2, 4, 7, 8, 9]  # (all error messages) empty for all

    [logging.ac]
    type = "AC"
    flush_int = 300 # seconds (5min)
    batch_size = 1000 # max batch size, force flush if reached this count.
    controllers = [] # empty for all controllers, or controllers keys
    levels = [2, 4, 7, 8, 9]  # (all error messages) empty for all

    [logging.console]
    type = "console"
    levels = [2, 4, 7, 8, 9]

[stats]
interval = 60 # seconds
controllers = [] # empty for all controllers, or controllers keys

[hubble]
controllers = [] # accept forwarding commands and connections from all controllers. Or specific controllers by name

[startup]
    [startup.legacy]
    name = "__legacy_daemon"
        [startup.legacy.args]
        max_restart = 10

    [startup.jumpscript]
    name = "__jumpscript_daemon"
        [startup.jumpscript.args]
        max_restart = 10
