[main]
Gid = 1
Nid = 10
MessageIdFile = "./.mid"
HistoryFile = "./.history"
AgentControllers = ["http://localhost:8966/"]

[cmds]
    [cmds.execute_js_py]
    Binary = "python2.7"
    Path = "./python"
    Script = "{name}.py"

    [cmds.sync]
    Binary = "python2.7"
    Path = "./python/sync"
    Script = "{name}.py"
    Env = ["PYTHONPATH=../"] # so scripts can load utils.py

[channel]
Cmds = [0] # long polling from agent 0

[logging]
    [logging.db]
    Type = "DB"
    LogDir = "./logs"
    Levels = [2, 4, 7, 8, 9]  # (all error messages) empty for all

    [logging.ac]
    Type = "AC"
    FlushInt = 300 # seconds (5min)
    BatchSize = 1000 # max batch size, force flush if reached this count.
    AgentControllers = [] # to all agents
    Levels = [2, 4, 7, 8, 9]  # (all error messages) empty for all

    [logging.console]
    Type = "console"
    Levels = [2, 4, 7, 8, 9]

[stats]
Interval = 60 # seconds
AgentControllers = []

