[main]
gid = 1
nid = 10
max_jobs = 100
message_id_file = "./.mid"
history_file = "./.history"
roles = []
include = "./conf"

[controllers]
    [controllers.main]
    url = "http://localhost:8966"
        [controllers.main.security]
        # UNCOMMENT THE FOLLOWING LINES TO USE SSL
        #client_certificate = "/path/to/client-test.crt"
        #client_certificate_key = "/path/to/client-test.key"

        # defines an extra CA to trust (used in case of server self-signed certs)
        # should be empty string otherwise.

        #certificate_authority = "/path/to/server.crt"

[channel]
cmds = [] # empty for long polling from all defined controllers, or specif controllers keys

[extensions]
    #the very basic agent extensions. Also please check the toml files under
    #the Main.Include folder for more extensions
    [extensions.sync]
    #syncthing extension
    binary = "python2.7"
    cwd = "./extensions/sync"
    args = ["{name}.py"]
        [extensions.sync.env]
        PYTHONPATH = "../:/opt/jumpscale7/lib"
        JUMPSCRIPTS_HOME = "/opt/jumpscale7/apps/agent2/jumpscripts/"
        SYNCTHING_URL = "http://localhost:28384"

    [extensions.jumpscript]
    binary = "python2.7"
    cwd = "./extensions/jumpscript"
    args = ["wrapper.py", "{domain}", "{name}"]
        [extensions.jumpscript.env]
        SOCKET = "/tmp/jumpscript.sock"
        PYTHONPATH = "../"

    [extensions.legacy]
    binary = "python2.7"
    cwd = "./extensions/legacy"
    args = ["wrapper.py"]
        [extensions.legacy.env]
        PYTHONPATH = "../" # for utils
        SOCKET = "/tmp/legacy.sock"

[logging]
    [logging.db]
    type = "DB"
    log_dir = "./logs"
    levels = [2, 4, 7, 8, 9, 11]  # (all error messages + debug) empty for all

    [logging.ac]
    type = "AC"
    flush_int = 300 # seconds (5min)
    batch_size = 1000 # max batch size, force flush if reached this count.
    controllers = [] # empty for all controllers, or controllers keys
    levels = [2, 4, 7, 8, 9, 11]  # (all error messages + debug) empty for all

    [logging.console]
    type = "console"
    levels = [2, 4, 7, 8, 9]

[stats]
interval = 60 # seconds
controllers = [] # empty for all controllers, or controllers keys

[hubble]
controllers = [] # accept forwarding commands and connections from all controllers. Or specific controllers by name

[startup]
#all startup commands has been moved to the sub ./conf folder
