[main]
Gid = 1
Nid = 10
MessageIdFile = "./.mid"
AgentControllers = ["http://localhost:8080/"]

[cmds]
    [cmds.execute_js_py]
    Binary = "python2.7"
    Path = "./python"

    [cmds.execute_js_lua]
    Binary = "lua"
    Path = "./lua"

[channel]
Cmds = [0] # long polling from agent 0

[logging]
    [logging.db]
    Type = "DB"
    LogDir = "./logs"
    Levels = []  # empty for all

    [logging.ac]
    Type = "AC"
    FlushInt = 300 # seconds (5min)
    BatchSize = 1000 # max batch size, force flush if reached this count.
    AgentControllers = [] # to all agents
    Levels = [2]

    [logging.console]
    Type = "console"
    Levels = [2, 4, 7, 8, 9]

[stats]
Interval = 60 # seconds
AgentControllers = []

