#leave /tmp and /opt/jumpscale8 in this file, gets replaced during installation

[main]
max_jobs = 200
message_ID_file = "/var/run/core.mid"

[channel]
cmds = [] # empty for long polling from all defined controllers, or specif controllers keys


[extension.bash]
binary = "bash"
args = ['-c', 'T=`mktemp` && cat > $T && bash $T; EXIT=$?; rm -rf $T; exit $EXIT']

[logging]
    [logging.db]
    type = "DB"
    address = "/var/log/g8os"
    levels = [2, 4, 7, 8, 9, 11]  # (all error messages + debug) empty for all

    #[logging.ac]
    #type = "AC"
    #flush_int = 300 # seconds (5min)
    #batch_size = 1000 # max batch size, force flush if reached this count.
    #controllers = [] # empty for all controllers, or controllers keys
    #levels = [2, 4, 7, 8, 9, 11]  # (all error messages + debug) empty for all

    [logging.console]
    type = "console"
    levels = [2, 4, 7, 8, 9]

[stats]
interval = 60000 # milliseconds (1 min)

[stats.ac]
enabled = false
controllers = [] # empty for all controllers, or controllers keys

[stats.redis]
enabled = false
flush_interval = 100 # millisecond
address = "localhost:6379"

[hubble]
controllers = [] # accept forwarding commands and connections from all controllers. Or specific controllers by name
