[network]
auto = true

#please leave the lo settings as is, otherwise your
#lo device won't have an IP.
[interface.lo]
protocol = "static"

[static.lo]
ip = "127.0.0.1/8"

[tap.port1]
up = true

[tap.port2]
up = true