# Start the ipfs daemon, after the networkin is already configured
[startup.ipfs-daemon]
name = "core.system"
after = ["net"]
running_match = "Daemon is ready"

[startup.ipfs-daemon.args]
name = "ipfs"
args = ["daemon", "--init"]


# add default nodes to IPFS
[startup.ipfs-bootstrap]
name = "core.system"
after = ["ipfs-daemon"]

[startup.ipfs-bootstrap.args]
name = "ipfs"
args = ["bootstrap", "add", "/ip4/37.59.7.72/tcp/4001/ipfs/QmRcqFGvwtfyCJuTrhrZYH4HrFnqNQkcxvAGhAJGdX5fE8"]


# make sure /ipfs and /ipns are in place so we start the mount
[startup.ipfs-mount-init]
name = "bash"
running_delay = -1

[startup.ipfs-mount-init.args]
stdin = """
mkdir -p /ipfs
mkdir -p /ipns
"""

[startup.ipfs-mount]
name = "core.system"
after = ["ipfs-daemon", "ipfs-mount-init"]

[startup.ipfs-mount.args]
name = "ipfs"
args = ["mount"]
