[startup.hostname]
name = "execute"
after = ["init"]
must_exit = true

[startup.hostname.args]
name = "hostname"
args = ["-F", "/etc/hostname"]

[startup.tty1]
name = "execute"
after = ["hostname"]

[startup.tty1.args]
name = "agetty"
args = ["tty1", "linux"]

[startup.tty2]
name = "execute"
after = ["hostname"]

[startup.tty2.args]
name = "agetty"
args = ["tty2", "linux"]

[startup.tty3]
name = "execute"
after = ["hostname"]

[startup.tty3.args]
name = "agetty"
args = ["tty3", "linux"]